dubbo:
  application:
    name: books_service
  protocol:
    port: -1
  registry:
    address: zookeeper://192.168.40.166:2181
  consumer:
    check: false

spring:
  datasource:
    url: jdbc:mysql:///db_books?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: com/qf/mapper/*.xml
